services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/bun.Dockerfile
    env_file: .env
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
  
  backend:
    build:
      context: .
      dockerfile: ./.docker/bun.Dockerfile
    env_file: .env
    volumes:
        - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: mariadb:11.6.2
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  dbdata: