services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  
  backend:
    build:
      context: ./backend
    env_file: .env
    ports:
      - "3000:3000"
  
  db:
    image: mariadb:11.6.2
    env_file: .env
    ports:
      - "3306:3306"

  nginx:
    buld:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend